server:
  port: 8090

spring:
  application:
    name: ms-zuul

eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka

zuul:
  routes:
    alumnos:
      serviceId: ms-alumnos
      path: /api/alumnos/**
    cursos:
      serviceId: ms-alumnos
      path: /api/cursos/**