server:
  port: 8090

spring:
  application:
    name: ms-zuul

eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka

zuul:
  routes:
    alumnos:
      serviceId: ms-alumnos
      path: /api/alumnos/**
    cursos:
      serviceId: ms-cursos
      path: /api/cursos/**
    examenes:
      serviceId: ms-examenes
      path: /api/examenes/**
    respuestas:
      serviceId: ms-respuestas
      path: /api/respuesta/**